### ISSUE TITLE
Show proper error when trying to use staking delegation with Ledger devices

### ISSUE THREAD

**Issue by Earlz** [qtumproject/qtum-electrum#113] opened 2021-02-18 22:04 UTC
Currently when trying to use a staking delegation from a Ledger paired wallet, the user will see this process flow:

* Prompt to sign message on Ledger
* Quickly disappearing confirmation that the signed message hash was received
* Quickly disappearing status updates on the bottom bar "preparing transaction"
* Freeze up of UI, requiring force quit. 

Ideally, we should detect that the Ledger app version can not support offline staking and present an appropriate error about this, rather than crudely giving a frozen app

**Comment by icodeface** [comment] 2021-02-19 01:31
will check the frozen issue, and ledger's official firmware has some issue signing contract call transaction, our modified firmware should work https://github.com/LedgerHQ/app-bitcoin/pull/176

**Comment by icodeface** [comment] 2021-02-19 01:39
there's an [offline staking version check](https://github.com/qtumproject/qtum-electrum/blob/master/electrum/plugins/ledger/ledger.py#L60) based on https://github.com/qtumproject/blue-app-btc/commits/update-qtum-sup, but i am not sure when it(https://github.com/LedgerHQ/app-bitcoin/pull/176) can get merged, and i hope ppl can use the fixed firmware without waiting for a new qtum-electrum release.

**Comment by Earlz** [comment] 2021-02-19 01:46
Please check if there is some workaround until we can easily deploy our modified firmware. This issue only seems to happen with 1.5.5 version of the Qtum app (which is the latest). With versions 1.5.4 and 1.4.7 there is no issue

**Comment by icodeface** [comment] 2021-02-19 01:47
> Please check if there is some workaround until we can easily deploy our modified firmware. This issue only seems to happen with 1.5.5 version of the Qtum app (which is the latest). With versions 1.5.4 and 1.4.7 there is no issue

yes, i think this commit https://github.com/qtumproject/blue-app-btc/commit/9169428210ce1c7f8b7ea28b6554e270d53ab4d8 might breaks the support, a size limit added in `btchip_output_script_is_op_call`

**Comment by Earlz** [comment] 2021-02-19 01:53
This seems like just a security update though and not one that should've broke things. It was also in the firmware for a lot longer than 1.5.5, I don't see how 1.4.7 would work but 1.5.5 would be broken from this

**Comment by icodeface** [comment] 2021-02-19 01:57
i cannot reproduce the frozen ui issue, will try more

**Comment by icodeface** [comment] 2021-02-19 02:04
> This seems like just a security update though and not one that should've broke things. It was also in the firmware for a lot longer than 1.5.5, I don't see how 1.4.7 would work but 1.5.5 would be broken from this

1.5.1 cannot work either.

**Closed** 2021-03-02 04:25 UTC
