### ISSUE TITLE
Qtum-electrum crashes after performing QIAIR to QI Swap

### ISSUE THREAD

**Issue by swiss8018** [qtumproject/qtum-electrum#114] opened 2021-02-26 20:33 UTC
Wallet crashes following swap from QIAIR to QI.  Initially attempted swap w/ QTUM core,  but did not work, repeated swap successfully with Electrum but now wallet crashes when launching.  Swap appears to have worked as my wallet shows a Qi balance.

Traceback
Traceback (most recent call last):
  File "electrum/gui/qt/history_list.py", line 80, in lessThan
  File "electrum/gui/qt/token_list.py", line 165, in data
  File "electrum/util.py", line 1243, in value_from_pos
KeyError: 2

**Comment by icodeface** [comment] 2021-02-27 09:33
thanks for reporting, the issue is fixed in https://github.com/qtumproject/qtum-electrum/commit/3a6f1281de42b31425b55d158eafe0fbe2d2a4e8, new release coming next week.

**Closed** 2021-03-02 04:25 UTC
